name: feems_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.3
  - geos
  - numpy==1.22.3 
  - scipy==1.5.0 
  - scikit-learn==0.23.1
  - matplotlib==3.2.2 
  - pyproj==2.6.1.post1 
  - networkx==2.4.0
  - shapely=1.7.1
  - fiona
  - pytest==5.4.3 
  - pep8==1.7.1 
  - flake8==3.8.3
  - click==7.1.2 
  - setuptools 
  - pandas-plink
  - msprime==1.0.0 
  - statsmodels==0.12.2 
  - PyYAML==5.4.1
  - xlrd==2.0.1
  - openpyxl==3.0.7
  - suitesparse=5.7.2
  - scikit-sparse=0.4.4
  - cartopy=0.18.0
